### ISSUE TITLE
How to access RunnerCommand.CommandData from test.dll?

### ISSUE THREAD

**Issue by bimwood** [StarkBIM/RvtTestRunner#2]
Hi Colin,
You've included a public static CommandData property in RunnerCommand, 'which is available for unit tests to use'. But when I try to access the property from my test code, it is set to null. How do I set this up properly, please?

I do this:
1. Open VS 2017, my up-to-date fork of RvtTestRunner.sln.
2. Start Revit 2016
3. Attach debugger. Breakpoint in RunnerCommand.Execute.
4. In Revit, start RvtRunner. Breakpoint is hit. CommandData has been set properly.
5. Continue. Hit NullReferenceException in my test: RunnerCommand.CommandData is null.

Now, in Debug/Modules, I can see that my test .dll is being loaded into a separate AppDomain, so it's not surprising that my code cannot see the original RvtTestRunner's CommandData. The new AppDomain has it's own, separate copy of RvtTestRunner, which isn't being initialized.

Is this something to do with the way XUnit is loading the test .dll, or do I need to set up my test project differently?

**Comment by starkcolin** [comment]
Hi David,

Yes, this has to do with how XUnit loads the DLLs.  The default setting is to load each test run into its own AppDomain.
PR #3 adds support for accessing the CommandData in test runs.  Support is optional, because it disables running tests in parallel and because it is generally safer to run the tests in their own AppDomain whenever possible.
A side effect of not running tests in their own AppDomain means that the DLLs are permanently loaded into that instance of Revit, meaning that it would not be possible to recompile them in Visual Studio.  So, I added the option to automatically copy DLLs to a temporary folder when running tests.  This allows for code to be modified without needing to close Revit.
Let me know if you have any issues.
